'use strict';
const num1 = Number(prompt('Please write first number'));
const num2 = Number(prompt('Please write second number'));
const plusResult = num1 + num2;
alert ('Result: ' + num1 + '+' + num2 + '=' + plusResult);
const minusResult = num1 - num2;
alert ('Result: ' + num1 + '-' + num2 + '=' + minusResult);
const multiolicationResult = num1 * num2;
alert ('Result: ' + num1 + '*' + num2 + '=' + multiolicationResult);
const divisionResult = num1 / num2;
alert ('Result: ' + num1 + '/' + num2 + '=' + divisionResult);